package vistas;

import dtos.EncargadoDTO;
import dtos.UsuarioDTO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class PantallaMenu extends javax.swing.JFrame {

    private UsuarioDTO usuario;
    
    /**
     * Creates new form PantallaInicioSesion
     * @param usuario
     * @param parent
     */
    public PantallaMenu(JFrame parent, UsuarioDTO usuario) {
        initComponents();
        setEnabled(true);
        this.setVisible(true);
        this.setTitle("SGVAPV - Menú");
        this.parent = parent;
        this.usuario = usuario;
        
        String[] partesNombre = usuario.getNombre().split(" ");
        
        lblNombreUsuario.setText("¡Hola, " + partesNombre[0] + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        btnVentaAgua = new javax.swing.JButton();
        lblNombreUsuario1 = new javax.swing.JLabel();
        btnVentaProductoVariado = new javax.swing.JButton();
        btnGestionarInventario = new javax.swing.JButton();
        btnReporteVentas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(196, 216, 255));
        setEnabled(false);
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));

        jPanel1.setBackground(new java.awt.Color(41, 136, 194));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Afacad", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA GENERAL DE VENTAS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo Agua Purificada del Valle.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(196, 216, 255));

        lblNombreUsuario.setFont(new java.awt.Font("Afacad", 1, 30)); // NOI18N
        lblNombreUsuario.setText("Hola, Diego");

        btnVentaAgua.setBackground(new java.awt.Color(41, 136, 194));
        btnVentaAgua.setFont(new java.awt.Font("Afacad", 1, 23)); // NOI18N
        btnVentaAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Water drop.png"))); // NOI18N
        btnVentaAgua.setText("VENTA DE AGUA");
        btnVentaAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaAguaActionPerformed(evt);
            }
        });

        lblNombreUsuario1.setFont(new java.awt.Font("Afacad", 1, 20)); // NOI18N
        lblNombreUsuario1.setText("¿QUÉ DESEAS HACER?");

        btnVentaProductoVariado.setBackground(new java.awt.Color(41, 136, 194));
        btnVentaProductoVariado.setFont(new java.awt.Font("Afacad", 1, 23)); // NOI18N
        btnVentaProductoVariado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Product.png"))); // NOI18N
        btnVentaProductoVariado.setText("VENTA DE PRODUCTO VARIADO");
        btnVentaProductoVariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaProductoVariadoActionPerformed(evt);
            }
        });

        btnGestionarInventario.setBackground(new java.awt.Color(41, 136, 194));
        btnGestionarInventario.setFont(new java.awt.Font("Afacad", 1, 23)); // NOI18N
        btnGestionarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Warehouse.png"))); // NOI18N
        btnGestionarInventario.setText("GESTIONAR INVENTARIO");
        btnGestionarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarInventarioActionPerformed(evt);
            }
        });

        btnReporteVentas.setBackground(new java.awt.Color(41, 136, 194));
        btnReporteVentas.setFont(new java.awt.Font("Afacad", 1, 23)); // NOI18N
        btnReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Financial Dynamic Presentation.png"))); // NOI18N
        btnReporteVentas.setText("GENERAR REPORTE DE VENTAS");
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(41, 136, 194));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout.png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNombreUsuario1)
                    .addComponent(lblNombreUsuario)
                    .addComponent(btnVentaAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentaProductoVariado, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnLogOut)
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(637, 637, 637)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblNombreUsuario1))
                    .addComponent(lblNombreUsuario))
                .addGap(40, 40, 40)
                .addComponent(btnVentaAgua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVentaProductoVariado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGestionarInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReporteVentas)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaAguaActionPerformed
        this.dispose();
        PantallaVenta pantallaVenta = new PantallaVenta(this, usuario);
        pantallaVenta.setTipoVenta("AGUA PURIFICADA");
    }//GEN-LAST:event_btnVentaAguaActionPerformed

    private void btnVentaProductoVariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaProductoVariadoActionPerformed
        this.dispose();
        PantallaVenta pantallaVenta = new PantallaVenta(this, usuario);
        pantallaVenta.setTipoVenta("PRODUCTO VARIADO");
    }//GEN-LAST:event_btnVentaProductoVariadoActionPerformed

    private void btnGestionarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarInventarioActionPerformed
        this.dispose();
        PantallaGestionarInventario pantallaInventario = new PantallaGestionarInventario(this,usuario);
    }//GEN-LAST:event_btnGestionarInventarioActionPerformed

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        if (usuario instanceof EncargadoDTO) {
            this.dispose();
            PantallaGenerarReporte pantallaReporte = new PantallaGenerarReporte(this, (EncargadoDTO) usuario);
            pantallaReporte.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No cuentas con los permisos necesarios para acceder.",
                    "Error de permisos.", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnReporteVentasActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarInventario;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JButton btnVentaAgua;
    private javax.swing.JButton btnVentaProductoVariado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNombreUsuario1;
    // End of variables declaration//GEN-END:variables
    private JFrame parent;
}
